name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: none

            - name: Lint PHP (safe even if no files)
        shell: bash
        run: |
          set -e
          files=$(find src public_html -type f -name "*.php" 2>/dev/null || true)
          if [ -z "$files" ]; then
            echo "No PHP files found to lint — skipping."
          else
            for f in $files; do
              echo "Linting $f"
              php -l "$f"
            done
          fi

      - name: Start built-in PHP server for health check
        run: |
          nohup php -S 127.0.0.1:8080 -t public_html > /dev/null 2>&1 &
          sleep 3

      - name: Health check
        run: |
          set -e
          echo "Requesting health endpoint..."
          curl -sSf http://127.0.0.1:8080/health.php | grep -qx 'OK'
          echo "Health endpoint OK"
